### PR TITLE
Prettier tables

### PR DESCRIPTION
**Pull request by Sebbito**
This commit changes two things:
1. how tables are indented
2. some logic

## Indents

I've stumbled upon this in one of my repositories where i had a table which itself had multiple tables inside of itself. The formatting came out a lot less readable than the input imo.

Here is the sample input (the first one was the table in question, the other ones are for testing different table types to see how the new formatting looks):

```lua
local coords = {
  { x = -5, y = 5 },
  { x = 5,  y = 5 },
  { x = -5, y = -5 },
  { x = 5,  y = -5 },
}

local test = {
  { name = "test", innerTable = { name = "even cooler test", evenInnerTable = { name = "wow so many inner tables" } } },
  { name = "test", innerTable = { name = "even cooler test", evenInnerTable = { name = "wow so many inner tables" } } },
}

local test = { name = "nice" }
```

Prettier would format it like this:

```lua
local coords = { {
        x = -5,
        y = 5,
}, {
        x = 5,
        y = 5,
}, {
        x = -5,
        y = -5,
}, {
        x = 5,
        y = -5,
} }

local test = { {
        name = "test",
        innerTable = {
                name = "even cooler test",
                evenInnerTable = { name = "wow so many inner tables" },
        },
}, {
        name = "test",
        innerTable = {
                name = "even cooler test",
                evenInnerTable = { name = "wow so many inner tables" },
        },
} }

local test = { name = "nice" }
```

I really dislike the double `{` on one line. Instead i changed it so that each line had max 1 curly brace:

```lua
local coords = {
        {
                x = -5,
                y = 5,
        },
        {
                x = 5,
                y = 5,
        },
        {
                x = -5,
                y = -5,
        },
        {
                x = 5,
                y = -5,
        },
}

local test = {
        {
                name = "test",
                innerTable = {
                        name = "even cooler test",
                        evenInnerTable = { name = "wow so many inner tables" },
                },
        },
        {
                name = "test",
                innerTable = {
                        name = "even cooler test",
                        evenInnerTable = { name = "wow so many inner tables" },
                },
        },
}

local test = { name = "nice" }
```

## Logic changes

I noticed that the previous function did the following:
1. Check if it was an empty table in which case it returns "{}"
2. calculate both single line and multi line table construction
3. decide which one to use based on the length of the node fields

Instead of calculating both single line and multi line and only then deciding which one to return we make use of the first if block and don't use `conditionalGroup`.

Note: In the [docs](https://github.com/prettier/prettier/blob/main/commands.md#conditionalgroup) the usage of `conditionalGroup` also seems to be discouraged:

`This should be used as last resort as it triggers an exponential complexity when nested.`

### CODE REVIEW

**Comment by suchipi** [comment]
Thank you for contributing! I think there is merit to this change. However, I updated the test snapshots by running `yarn test -u`, and some of the changes are undesirable (notably, the cases where tables with two items always get broken across lines). Maybe instead of breaking based on number of items in the table, we could break based on whether the line is over the column limit? It's been a while since I worked in this repo, but I think you can accomplish that by using `softline` instead of `hardline`.

**Comment by Sebbito** [comment]
Yes that sounds like a good idea! I will look into that.

Also sorry for ignoring the test suite. I will check it next time ^^'

**Comment by Sebbito** [comment]
In 6afe866 I've changed the logic to use a `fill` instead of a concat and use `ifBreaks` to keep the hard linebreaks in this style:

```lua
local table = {
    ...
}
```

otherwise it would have looked like this:

```lua
local table =
    {
        ...
    }
```

But as you saw i noticed that this lead to some (imo) ugly things that happen when you do some OOP style function definitions in tables. Sadly I don't know a whole lot about prettier and spending 2h on this change alone is more than I'd like to have spent xD

**Comment by Sebbito** [comment]
Well...I'm back and i wanted to close this issue for good. Some more hours poured into this but it seems like i can't fix this.

Some things I've noticed: `concat()` seems to be outdated. I can't find anything about the function in the docs. The only place to find any info is in the index.d.ts file in the project which states:

```
/**
  * @see [concat](https://github.com/prettier/prettier/blob/main/commands.md#deprecated-concat)
  * @deprecated use `Doc[]` instead
  */
```
(the link that is mentioned is dead)

If you just remove the function as the comment suggests, the behavior changes and the code breaks.

Either way with me not wanting to put in a lot more hours and no one working on this project I'll make the call to close this PR in a week.

It's unfortunate that i couldn't resolve the last little detail but it is what it is.

**Pull request closed without merging**
